![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references. You will work on your own but remember the teaching staff is at your service whenever you encounter problems.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [6]:
print(np.__version__)

1.20.0


#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [37]:
a = np.random.rand(3,2,5)

print(a)

[[[0.95020819 0.23372708 0.60621032 0.97668264 0.8476832 ]
  [0.24186193 0.93364451 0.11258514 0.04642932 0.26826951]]

 [[0.73935401 0.71569741 0.08746166 0.79239495 0.17579891]
  [0.98888319 0.72165554 0.66200275 0.1823939  0.15356641]]

 [[0.28399676 0.73879469 0.29313274 0.61564585 0.01688049]
  [0.83440109 0.83479266 0.77208393 0.83132692 0.85791195]]]


In [40]:
a = np.random.randn(3, 2, 5)

print(a)

[[[-2.26381484e-01 -6.93795465e-01  1.41629794e+00  5.97330421e-01
    1.34040195e+00]
  [-2.80732412e+00  1.05503490e-03 -9.36717685e-01  4.32250298e-01
   -6.74565076e-01]]

 [[-1.35043762e+00 -1.88646434e+00 -8.05522878e-01 -1.44067559e+00
    1.34735921e+00]
  [ 6.32040144e-01  1.51403675e+00 -1.33428763e+00 -6.40666297e-01
    1.09857061e+00]]

 [[ 6.00831993e-01  1.94996263e-02 -1.10733660e+00  1.78235641e-01
   -1.06184467e+00]
  [-7.61500461e-01  5.94453982e-01  1.27967420e+00 -5.23898755e-01
   -1.84279978e+00]]]


In [42]:
a = np.arange(30).reshape(3,2,5)

print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [44]:
a = np.empty((3,2,5))

print(a)

[[[2.26381484e-01 6.93795465e-01 1.41629794e+00 5.97330421e-01
   1.34040195e+00]
  [2.80732412e+00 1.05503490e-03 9.36717685e-01 4.32250298e-01
   6.74565076e-01]]

 [[1.35043762e+00 1.88646434e+00 8.05522878e-01 1.44067559e+00
   1.34735921e+00]
  [6.32040144e-01 1.51403675e+00 1.33428763e+00 6.40666297e-01
   1.09857061e+00]]

 [[6.00831993e-01 1.94996263e-02 1.10733660e+00 1.78235641e-01
   1.06184467e+00]
  [7.61500461e-01 5.94453982e-01 1.27967420e+00 5.23898755e-01
   1.84279978e+00]]]


#### 4. Print *a*.


In [45]:
# your code here
print(a)

[[[2.26381484e-01 6.93795465e-01 1.41629794e+00 5.97330421e-01
   1.34040195e+00]
  [2.80732412e+00 1.05503490e-03 9.36717685e-01 4.32250298e-01
   6.74565076e-01]]

 [[1.35043762e+00 1.88646434e+00 8.05522878e-01 1.44067559e+00
   1.34735921e+00]
  [6.32040144e-01 1.51403675e+00 1.33428763e+00 6.40666297e-01
   1.09857061e+00]]

 [[6.00831993e-01 1.94996263e-02 1.10733660e+00 1.78235641e-01
   1.06184467e+00]
  [7.61500461e-01 5.94453982e-01 1.27967420e+00 5.23898755e-01
   1.84279978e+00]]]


In [50]:
a= np.random.random((3,2,5))
print(a)

[[[0.71796157 0.22591105 0.94494076 0.57672051 0.77228346]
  [0.37943042 0.23963207 0.10297085 0.98763433 0.78351914]]

 [[0.96567752 0.28791439 0.76922141 0.67428566 0.46712852]
  [0.69982027 0.12426514 0.72201695 0.09457751 0.20999098]]

 [[0.43475582 0.81807411 0.60675934 0.87088941 0.6211472 ]
  [0.369234   0.23713139 0.79413356 0.40596531 0.19351055]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [47]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [48]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [52]:
# your code here

a.size

30

In [53]:
b.size

#yes, a and b have the same size!

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [55]:
# your answer here

addarrays = np.add(a, b)  
print (addarrays) 

# No, because shape numbers are different

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [60]:
b.shape

(5, 2, 3)

In [63]:
c = b.reshape(3,2,5)

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [66]:
# your code/answer here
d = np.add(a,c)  
print (d) 

# yes! It works now.

[[[1.71796157 1.22591105 1.94494076 1.57672051 1.77228346]
  [1.37943042 1.23963207 1.10297085 1.98763433 1.78351914]]

 [[1.96567752 1.28791439 1.76922141 1.67428566 1.46712852]
  [1.69982027 1.12426514 1.72201695 1.09457751 1.20999098]]

 [[1.43475582 1.81807411 1.60675934 1.87088941 1.6211472 ]
  [1.369234   1.23713139 1.79413356 1.40596531 1.19351055]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [72]:
# your code/answer here

print(a)

[[[0.71796157 0.22591105 0.94494076 0.57672051 0.77228346]
  [0.37943042 0.23963207 0.10297085 0.98763433 0.78351914]]

 [[0.96567752 0.28791439 0.76922141 0.67428566 0.46712852]
  [0.69982027 0.12426514 0.72201695 0.09457751 0.20999098]]

 [[0.43475582 0.81807411 0.60675934 0.87088941 0.6211472 ]
  [0.369234   0.23713139 0.79413356 0.40596531 0.19351055]]]


In [71]:
# your code/answer here

print(d)

# d has +1 in every value.

[[[1.71796157 1.22591105 1.94494076 1.57672051 1.77228346]
  [1.37943042 1.23963207 1.10297085 1.98763433 1.78351914]]

 [[1.96567752 1.28791439 1.76922141 1.67428566 1.46712852]
  [1.69982027 1.12426514 1.72201695 1.09457751 1.20999098]]

 [[1.43475582 1.81807411 1.60675934 1.87088941 1.6211472 ]
  [1.369234   1.23713139 1.79413356 1.40596531 1.19351055]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [73]:
# your code here
e = a * c

In [74]:
a

array([[[0.71796157, 0.22591105, 0.94494076, 0.57672051, 0.77228346],
        [0.37943042, 0.23963207, 0.10297085, 0.98763433, 0.78351914]],

       [[0.96567752, 0.28791439, 0.76922141, 0.67428566, 0.46712852],
        [0.69982027, 0.12426514, 0.72201695, 0.09457751, 0.20999098]],

       [[0.43475582, 0.81807411, 0.60675934, 0.87088941, 0.6211472 ],
        [0.369234  , 0.23713139, 0.79413356, 0.40596531, 0.19351055]]])

In [75]:
e

array([[[0.71796157, 0.22591105, 0.94494076, 0.57672051, 0.77228346],
        [0.37943042, 0.23963207, 0.10297085, 0.98763433, 0.78351914]],

       [[0.96567752, 0.28791439, 0.76922141, 0.67428566, 0.46712852],
        [0.69982027, 0.12426514, 0.72201695, 0.09457751, 0.20999098]],

       [[0.43475582, 0.81807411, 0.60675934, 0.87088941, 0.6211472 ],
        [0.369234  , 0.23713139, 0.79413356, 0.40596531, 0.19351055]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [76]:
# your code/answer here

#yes! equal, because c is all 1 values.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [79]:
# your code here

d_max = d.max()

d_max

1.9876343260043665

In [80]:
d_min = d.min()

d_min

1.0945775114865357

In [81]:
d_mean = d.mean()

d_mean

1.536583438665443

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [99]:
# your code here

f = np.empty(shape=(3,2,5))

f

array([[[0.71796157, 0.22591105, 0.94494076, 0.57672051, 0.77228346],
        [0.37943042, 0.23963207, 0.10297085, 0.98763433, 0.78351914]],

       [[0.96567752, 0.28791439, 0.76922141, 0.67428566, 0.46712852],
        [0.69982027, 0.12426514, 0.72201695, 0.09457751, 0.20999098]],

       [[0.43475582, 0.81807411, 0.60675934, 0.87088941, 0.6211472 ],
        [0.369234  , 0.23713139, 0.79413356, 0.40596531, 0.19351055]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [108]:
for number in f:
    if d_mean > d > d_min: 
        print('25')
    elif d_mean < d < d_max:
        print('75')
    elif d_mean == d:
        print('50')
    elif d_mean in d:
        print('0')
    elif d_max in d:
        print('100')
    else:
        print('0')
    

AttributeError: 'numpy.ndarray' object attribute 'any' is read-only

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],

[[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],

[[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
 [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
```

In [0]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here

## Additional Challenges for the Nerds

If you are way ahead of your classmates and willing to accept some tough challenges about Numpy, take one or several of the following Codewar *katas*. 	You need to already possess a good amount of knowledge in Python and statistics because you will need to write Python functions, do loops, write conditionals, and deal with matrices.

* [Insert dashes](https://www.codewars.com/kata/insert-dashes)
* [Thinkful - Logic Drills: Red and bumpy](https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy)